### ISSUE TITLE
expo sdk 21 warning

### ISSUE THREAD

**Issue by unbegrenzt** [perushevandkhmelev-agency/react-native-material-textinput#18]
be sure you're not retrieving this in expo sdk 51

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-05-15 at 09 07 11](https://github.com/perushevandkhmelev-agency/react-native-material-textinput/assets/19624703/7c907af0-7556-419e-b68f-d077d4308508)

**Comment by maximpostnikov** [comment]
Try v1.4.2, where I removed static defaultProps in favor of js default parameters

**Comment by unbegrenzt** [comment]
> Try v1.4.2, where I removed static defaultProps in favor of js default parameters

It works
